version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Monterrey
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
