version: 0.11.1
version_files:
  - packages/better_auth/lib/better_auth/version.rb
  - packages/better_auth-cli/lib/better_auth/cli/version.rb
  - packages/better_auth-api-key/lib/better_auth/api_key/version.rb
  - packages/better_auth-grape/lib/better_auth/grape/version.rb
  - packages/better_auth-hanami/lib/better_auth/hanami/version.rb
  - packages/better_auth-mongo-adapter/lib/better_auth/mongo_adapter/version.rb
  - packages/better_auth-mongodb/lib/better_auth/mongodb/version.rb
  - >-
    packages/better_auth-oauth-provider/lib/better_auth/oauth_provider/version.rb
  - packages/better_auth-passkey/lib/better_auth/passkey/version.rb
  - packages/better_auth-rails/lib/better_auth/rails/version.rb
  - packages/better_auth-redis-storage/lib/better_auth/redis_storage/version.rb
  - packages/better_auth-roda/lib/better_auth/roda/version.rb
  - packages/better_auth-scim/lib/better_auth/scim/version.rb
  - packages/better_auth-sinatra/lib/better_auth/sinatra/version.rb
  - packages/better_auth-oidc/lib/better_auth/oidc/version.rb
  - packages/better_auth-saml/lib/better_auth/saml/version.rb
  - packages/better_auth-sso/lib/better_auth/sso/version.rb
  - packages/better_auth-stripe/lib/better_auth/stripe/version.rb
  - packages/better_auth-telemetry/lib/better_auth/telemetry/version.rb
