# frozen_string_literal: true

require "base64"
require "cgi"
require "json"
require "jwt"
require "net/http"
require "openssl"
require "rexml/document"
require "resolv"
require "securerandom"
require "time"
require "uri"
require "zlib"

require_relative "../sso/plugin/core"
require_relative "../sso/plugin/oidc_discovery"
require_relative "../sso/plugin/providers"
require_relative "../sso/plugin/sign_in_and_oidc_callbacks"
require_relative "../sso/plugin/endpoints"
require_relative "../sso/plugin/saml_response"
require_relative "../sso/plugin/saml_metadata_and_logout"
require_relative "../sso/plugin/saml_validation_and_state"
require_relative "../sso/plugin/oidc_runtime"
require_relative "../sso/plugin/provider_utils"
