#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "time"
require_relative "support/endpoint_naming"

ROOT = File.expand_path("..", __dir__)
UPSTREAM_REGISTRY = File.join(ROOT, "reference", "upstream-endpoint-registry.json")
RUBY_INVENTORY = File.join(ROOT, "reference", "endpoints-inventory.json")
OUTPUT_MD = File.join(ROOT, "reference", "endpoints-api-comparison.md")
OUTPUT_JSON = File.join(ROOT, "reference", "endpoints-api-comparison.json")

SKIP_PLUGINS = %w[mcp electron oidc-provider].freeze
SKIP_PATHS = %w[/forget-password/email-otp].freeze
PASSKEY_METHOD_OVERRIDES = {
  "GET /passkey/generate-authenticate-options" => "POST",
  "GET /passkey/generate-register-options" => "POST"
}.freeze

module EndpointApiComparison
  module_function

  def run!
    upstream_rows = load_upstream_registry
    ruby_rows = load_ruby_inventory
    report = build_report(upstream_rows, ruby_rows)
    write_markdown(report)
    write_json(report)
    print_summary(report)
    exit((report[:registry_key_mismatch_count].positive? || report[:missing_ruby_count].positive?) ? 1 : 0)
  end

  def load_upstream_registry
    registry = JSON.parse(File.read(UPSTREAM_REGISTRY))
    registry.fetch("entries").map do |row|
      row.transform_keys(&:to_sym).merge(
        ruby_registry_key: row["ruby_registry_key"] || EndpointNaming.upstream_registry_key_to_ruby(row["registry_key"])
      )
    end
  end

  def load_ruby_inventory
    inventory = JSON.parse(File.read(RUBY_INVENTORY))
    inventory.fetch("routes").map do |row|
      row.transform_keys(&:to_sym)
    end
  end

  def build_report(upstream_rows, ruby_rows)
    ruby_index = ruby_rows.each_with_object({}) do |row, index|
      index[[row[:path], row[:method].to_s.upcase]] = row
    end
    ruby_by_path = ruby_rows.group_by { |row| row[:path] }

    aligned = []
    registry_key_mismatches = []
    missing_ruby = []
    deprecated_pairs = []

    comparable_upstream = upstream_rows.reject do |upstream|
      SKIP_PLUGINS.include?(upstream[:plugin_id].to_s) || SKIP_PATHS.include?(upstream[:path].to_s)
    end

    comparable_upstream.group_by { |upstream| upstream_group_key(upstream) }.each do |_key, group|
      upstream = group.first
      ruby = find_ruby_row(ruby_index, ruby_by_path, upstream)

      if ruby.nil?
        missing_ruby << upstream unless upstream[:deprecated] || group.all? { |entry| entry[:deprecated] }
        next
      end

      matching = group.find { |entry| registry_entry_matches_ruby?(entry, ruby) }
      pair = (matching || upstream).merge(
        ruby_endpoint_key: ruby[:endpoint_key],
        ruby_api_method: ruby[:ruby_api_method],
        ruby_api_call: ruby[:ruby_api_call],
        ruby_plugin: ruby[:plugin_id] || ruby[:plugin_hint]
      )

      if group.any? { |entry| entry[:deprecated] } && !matching
        deprecated_pairs << pair
      elsif matching
        aligned << pair
      else
        registry_key_mismatches << pair
      end
    end

    missing_upstream = ruby_rows.reject do |ruby|
      upstream_rows.any? do |upstream|
        upstream[:path] == ruby[:path] && upstream[:method].to_s.upcase == ruby[:method].to_s.upcase
      end
    end

    email_otp_focus = (aligned + registry_key_mismatches + deprecated_pairs + missing_ruby)
      .select { |row| row[:path].to_s.include?("email-otp") || row[:path].to_s.include?("forget-password") }
      .uniq { |row| [row[:path], row[:method]] }
      .sort_by { |row| [row[:path], row[:method].to_s] }

    {
      generated_at: Time.now.utc.iso8601,
      upstream_route_count: upstream_rows.length,
      ruby_route_count: ruby_rows.length,
      aligned_count: aligned.length,
      registry_key_mismatch_count: registry_key_mismatches.length,
      api_name_mismatch_count: registry_key_mismatches.length,
      missing_ruby_count: missing_ruby.length,
      missing_upstream_count: missing_upstream.length,
      deprecated_pair_count: deprecated_pairs.length,
      aligned: aligned,
      registry_key_mismatches: registry_key_mismatches,
      api_name_mismatches: registry_key_mismatches,
      missing_ruby: missing_ruby,
      missing_upstream: missing_upstream,
      deprecated_pairs: deprecated_pairs,
      email_otp_focus: email_otp_focus
    }
  end

  def write_markdown(report)
    lines = []
    lines << "# Upstream vs RubyAuth API naming comparison"
    lines << ""
    lines << "Auto-generated by `scripts/compare-endpoint-api-names.rb`."
    lines << ""
    lines << "- **Generated at**: #{report[:generated_at]}"
    lines << "- **Upstream registry entries**: #{report[:upstream_route_count]} (`reference/upstream-endpoint-registry.json`)"
    lines << "- **Ruby routes**: #{report[:ruby_route_count]} (`reference/endpoints-inventory.json`)"
    lines << "- **Aligned registry keys**: #{report[:aligned_count]}"
    lines << "- **Registry key mismatches**: #{report[:registry_key_mismatch_count]}"
    lines << "- **Missing in Ruby inventory**: #{report[:missing_ruby_count]}"
    lines << "- **Ruby-only / not found upstream**: #{report[:missing_upstream_count]}"
    lines << "- **Deprecated upstream pairs still in Ruby**: #{report[:deprecated_pair_count]}"
    lines << ""
    lines << "Naming policy: `reference/ruby-api-naming-policy.md`"
    lines << ""
    lines << "## Email OTP password reset focus"
    lines << ""
    lines << "| Method | Path | Upstream registry key | Ruby registry key | Status |"
    lines << "| --- | --- | --- | --- | --- |"

    report[:email_otp_focus].each do |row|
      status = email_otp_status(row, report)
      lines << "| #{row[:method]} | `#{row[:path]}` | `#{row[:registry_key]}` | `#{row[:ruby_endpoint_key] || "-"}` | #{status} |"
    end

    sections = [
      ["Registry key mismatches (path matches, canonical key differs)", :registry_key_mismatches, mismatch_row],
      ["Deprecated upstream routes still present in Ruby", :deprecated_pairs, deprecated_row],
      ["Missing in Ruby inventory (non-deprecated upstream)", :missing_ruby, upstream_only_row],
      ["Ruby-only routes (not found upstream registry)", :missing_upstream, ruby_only_row]
    ]

    sections.each do |title, key, formatter|
      rows = report[key]
      next if rows.empty?

      lines << ""
      lines << "## #{title}"
      lines << ""
      lines << formatter[:header]
      lines << formatter[:divider]
      rows.first(100).each { |row| lines << formatter[:row].call(row) }
      lines << ""
      lines << "_Showing #{[rows.length, 100].min} of #{rows.length}._" if rows.length > 100
    end

    lines << ""
    lines << "## Re-run"
    lines << ""
    lines << "```bash"
    lines << "ruby scripts/generate-upstream-endpoint-registry.rb"
    lines << "ruby scripts/generate-endpoint-inventory.rb"
    lines << "ruby scripts/compare-endpoint-api-names.rb"
    lines << "```"
    lines << ""

    File.write(OUTPUT_MD, lines.join("\n"))
  end

  def upstream_group_key(upstream)
    [upstream[:path], normalized_upstream_method(upstream)]
  end

  def normalized_upstream_method(upstream)
    override = PASSKEY_METHOD_OVERRIDES["#{upstream[:method].to_s.upcase} #{upstream[:path]}"]
    return override if override

    upstream[:method].to_s.upcase
  end

  def find_ruby_row(ruby_index, ruby_by_path, upstream)
    method = normalized_upstream_method(upstream)
    return ruby_index[[upstream[:path], method]] if method != "*"

    rows = ruby_by_path[upstream[:path]] || []
    rows.find { |row| row[:method].to_s.upcase == "GET" } || rows.first
  end

  def registry_entry_matches_ruby?(upstream, ruby)
    EndpointNaming.registry_keys_equivalent?(upstream[:registry_key], ruby[:endpoint_key])
  end

  def email_otp_status(row, report)
    if row[:deprecated]
      "deprecated upstream"
    elsif report[:registry_key_mismatches].any? { |entry| entry[:path] == row[:path] && entry[:method] == row[:method] }
      "registry key mismatch"
    elsif report[:missing_ruby].any? { |entry| entry[:path] == row[:path] && entry[:method] == row[:method] }
      "missing ruby"
    elsif row[:ruby_endpoint_key]
      "aligned"
    else
      "unknown"
    end
  end

  def mismatch_row
    {
      header: "| Path | Upstream registry key | Expected Ruby key | Ruby endpoint key |",
      divider: "| --- | --- | --- | --- |",
      row: ->(row) {
        expected = EndpointNaming.upstream_registry_key_to_ruby(row[:registry_key])
        "| `#{row[:method]} #{row[:path]}` | `#{row[:registry_key]}` | `#{expected}` | `#{row[:ruby_endpoint_key] || "-"}` |"
      }
    }
  end

  def deprecated_row
    {
      header: "| Path | Upstream registry key | Ruby endpoint key | Notes |",
      divider: "| --- | --- | --- | --- |",
      row: ->(row) {
        "| `#{row[:method]} #{row[:path]}` | `#{row[:registry_key]}` | `#{row[:ruby_endpoint_key] || "-"}` | deprecated upstream route |"
      }
    }
  end

  def upstream_only_row
    {
      header: "| Path | Upstream registry key | Expected Ruby key | Source |",
      divider: "| --- | --- | --- | --- |",
      row: ->(row) {
        "| `#{row[:method]} #{row[:path]}` | `#{row[:registry_key]}` | `#{row[:ruby_registry_key]}` | `#{row[:source_file]}` |"
      }
    }
  end

  def ruby_only_row
    {
      header: "| Path | Ruby endpoint key | Plugin |",
      divider: "| --- | --- | --- |",
      row: ->(row) {
        "| `#{row[:method]} #{row[:path]}` | `#{row[:endpoint_key] || "-"}` | `#{row[:plugin_id] || row[:plugin_hint] || "-"}` |"
      }
    }
  end

  def write_json(report)
    File.write(OUTPUT_JSON, JSON.pretty_generate(stringify_keys(report)))
  end

  def stringify_keys(value)
    case value
    when Hash
      value.each_with_object({}) { |(key, object), result| result[key.to_s] = stringify_keys(object) }
    when Array
      value.map { |entry| stringify_keys(entry) }
    else
      value
    end
  end

  def print_summary(report)
    puts "Wrote #{OUTPUT_MD}"
    puts "Wrote #{OUTPUT_JSON}"
    puts "Upstream: #{report[:upstream_route_count]} | Ruby: #{report[:ruby_route_count]} | Aligned: #{report[:aligned_count]}"
    puts "Registry key mismatches: #{report[:registry_key_mismatch_count]} | Missing Ruby: #{report[:missing_ruby_count]} | Ruby-only: #{report[:missing_upstream_count]} | Deprecated pairs: #{report[:deprecated_pair_count]}"
  end
end

EndpointApiComparison.run!
