# frozen_string_literal: true

require_relative "../../test_helper"
require "better_auth/sql_migration"
require "sqlite3"

class BetterAuthMigrationSQLTest < Minitest::Test
  SECRET = "test-secret-that-is-long-enough-for-validation"

  class FakeSQLAdapter < BetterAuth::Adapters::Base
    attr_reader :connection, :dialect

    def initialize(options, connection)
      super(options)
      @connection = connection
      @dialect = :postgres
    end
  end

  class FakeSQLiteAdapter < BetterAuth::Adapters::Base
    attr_reader :connection, :dialect

    def initialize(options, connection)
      super(options)
      @connection = connection
      @dialect = :sqlite
    end
  end

  class FakeSQLConnection
    attr_reader :executed_statements, :applied_versions

    def initialize(select_error: nil)
      @executed_statements = []
      @applied_versions = []
      @select_error = select_error
    end

    def exec(statement)
      @executed_statements << statement

      if statement.match?(/SELECT .*better_auth_schema_migrations/i)
        raise @select_error if @select_error

        applied_versions.map { |version| {"version" => version} }
      elsif (match = statement.match(/VALUES \('([^']+)'\)/))
        @applied_versions << match[1]
        []
      else
        []
      end
    end
  end

  def test_renders_sql_migration_with_plugin_schema
    plugin = BetterAuth::Plugin.new(
      id: "api-key-test",
      schema: {
        apiKey: {
          model_name: "api_keys",
          fields: {
            id: {type: "string", required: true},
            userId: {type: "string", required: true, references: {model: "user", field: "id"}, index: true},
            key: {type: "string", required: true, unique: true}
          }
        }
      }
    )
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory, plugins: [plugin])

    sql = BetterAuth::SQLMigration.render(config, dialect: :postgres, generator: "better_auth-test")

    assert_includes sql, "-- Generated by better_auth-test"
    assert_includes sql, "-- Dialect: postgres"
    assert_includes sql, 'CREATE TABLE IF NOT EXISTS "users"'
    assert_includes sql, 'CREATE TABLE IF NOT EXISTS "api_keys"'
  end

  def test_executes_pending_sql_migrations_once
    Dir.mktmpdir("better-auth-core-migrate") do |dir|
      migrations_path = File.join(dir, "db/better_auth/migrate")
      FileUtils.mkdir_p(migrations_path)
      File.write(
        File.join(migrations_path, "20260427000000_create_better_auth_tables.sql"),
        "CREATE TABLE users (id text PRIMARY KEY);\nCREATE INDEX index_users_on_email ON users (email);\n"
      )
      connection = FakeSQLConnection.new
      auth = BetterAuth.auth(
        secret: SECRET,
        database: ->(options) { FakeSQLAdapter.new(options, connection) }
      )

      BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)
      BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)

      assert_equal 1, connection.executed_statements.count("CREATE TABLE users (id text PRIMARY KEY)")
      assert_equal 1, connection.executed_statements.count("CREATE INDEX index_users_on_email ON users (email)")
      assert_equal ["20260427000000_create_better_auth_tables.sql"], connection.applied_versions
    end
  end

  def test_plans_all_tables_for_empty_database
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)

    assert_equal %w[users sessions accounts verifications], plan.to_create.map(&:table_name)
    assert_empty plan.to_add
    assert_empty plan.warnings
  end

  def test_plans_only_missing_additional_fields_and_indexes_for_existing_tables
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    base_config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)
    BetterAuth::SQLMigration.execute_sql(
      connection,
      BetterAuth::Schema::SQL.create_statements(base_config, dialect: :sqlite).join("\n")
    )
    config = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      user: {
        additional_fields: {
          role: {type: "string", required: false, index: true}
        }
      }
    )

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)
    sql = BetterAuth::SQLMigration.render_pending(config, connection: connection, dialect: :sqlite, generator: "better_auth-test")

    assert_empty plan.to_create
    assert_equal ["users"], plan.to_add.map(&:table_name)
    assert_equal ["role"], plan.to_add.first.fields.keys
    assert_equal ["index_users_on_role"], plan.to_index.map(&:name)
    assert_includes sql, 'ALTER TABLE "users" ADD COLUMN "role" text'
    assert_includes sql, 'CREATE INDEX IF NOT EXISTS "index_users_on_role" ON "users" ("role")'
    refute_includes sql, 'CREATE TABLE IF NOT EXISTS "users"'
  end

  def test_plans_plugin_table_after_initial_core_schema
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    base_config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)
    BetterAuth::SQLMigration.execute_sql(
      connection,
      BetterAuth::Schema::SQL.create_statements(base_config, dialect: :sqlite).join("\n")
    )
    plugin = BetterAuth::Plugin.new(
      id: "api-key-test",
      schema: {
        apiKey: {
          model_name: "api_keys",
          fields: {
            id: {type: "string", required: true},
            userId: {type: "string", required: true, references: {model: "user", field: "id"}, index: true},
            key: {type: "string", required: true, unique: true}
          }
        }
      }
    )
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory, plugins: [plugin])

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)

    assert_equal ["api_keys"], plan.to_create.map(&:table_name)
    assert_empty plan.to_add
    assert_equal ["index_api_keys_on_user_id"], plan.to_index.map(&:name)
  end

  def test_postgres_pending_migration_backfills_missing_plugin_id_columns
    plugin = BetterAuth::Plugin.new(
      id: "idless-plugin",
      schema: {
        apiKey: {
          model_name: "api_keys",
          fields: {
            key: {type: "string", required: true}
          }
        }
      }
    )
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory, plugins: [plugin])
    existing = BetterAuth::Schema.auth_tables(BetterAuth::Configuration.new(secret: SECRET, database: :memory)).each_with_object({}) do |(_logical, table), schema|
      schema[table.fetch(:model_name)] = {
        name: table.fetch(:model_name),
        columns: table.fetch(:fields).to_h do |field, attributes|
          type = (attributes[:type] == "date") ? "timestamptz" : "text"
          [attributes[:field_name] || BetterAuth::Schema.send(:physical_name, field), type]
        end,
        indexes: {names: Set.new, columns: Set.new, unique_columns: Set.new}
      }
    end
    existing["api_keys"] = {name: "api_keys", columns: {"key" => "text"}, indexes: {names: Set.new, columns: Set.new, unique_columns: Set.new}}

    plan = BetterAuth::SQLMigration.plan_from_existing(config, existing: existing, dialect: :postgres)
    sql = BetterAuth::Schema::SQL.pending_statements(plan).join("\n")

    assert_includes sql, 'ALTER TABLE "api_keys" ADD COLUMN "id" text;'
    assert_includes sql, 'UPDATE "api_keys" SET "id" = md5'
    assert_includes sql, 'ALTER TABLE "api_keys" ALTER COLUMN "id" SET NOT NULL;'
    assert_includes sql, 'ALTER TABLE "api_keys" ADD PRIMARY KEY ("id");'
    refute_includes sql, 'ADD COLUMN "id" text PRIMARY KEY NOT NULL'
  end

  def test_mssql_pending_migration_preserves_filtered_unique_indexes_for_nullable_fields
    config = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      plugins: [BetterAuth::Plugins.phone_number]
    )

    plan = BetterAuth::SQLMigration.plan_from_existing(
      config,
      existing: {
        "users" => {
          name: "users",
          columns: {
            "id" => "varchar",
            "name" => "varchar",
            "email" => "varchar",
            "email_verified" => "smallint",
            "image" => "varchar",
            "created_at" => "datetime2",
            "updated_at" => "datetime2",
            "phone_number" => "varchar",
            "phone_number_verified" => "smallint"
          },
          indexes: BetterAuth::SQLMigration.empty_index_metadata
        }
      },
      dialect: :mssql
    )
    sql = BetterAuth::Schema::SQL.pending_statements(plan).join("\n")

    assert_includes sql, "CREATE UNIQUE INDEX [uniq_users_phone_number] ON [users] ([phone_number]) WHERE [phone_number] IS NOT NULL"
    refute_includes sql, "CONSTRAINT [uniq_users_phone_number] UNIQUE ([phone_number])"
  end

  def test_warns_on_type_mismatch_without_planning_destructive_alter
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    connection.execute('CREATE TABLE "users" ("id" text PRIMARY KEY, "email" integer);')
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)

    assert plan.warnings.any? { |warning| warning.include?("users.email") && warning.include?("string") && warning.include?("integer") }
    refute plan.to_add.any? { |change| change.table_name == "users" && change.fields.key?("email") }
  end

  def test_does_not_record_sql_file_migration_when_statement_fails
    Dir.mktmpdir("better-auth-core-migrate-failure") do |dir|
      migrations_path = File.join(dir, "db/better_auth/migrate")
      FileUtils.mkdir_p(migrations_path)
      File.write(
        File.join(migrations_path, "20260427000000_create_better_auth_tables.sql"),
        "CREATE TABLE users (id text PRIMARY KEY);\nBROKEN;\n"
      )
      connection = FakeSQLConnection.new
      def connection.exec(statement)
        raise "broken migration statement" if statement.include?("BROKEN")

        super
      end
      auth = BetterAuth.auth(
        secret: SECRET,
        database: ->(options) { FakeSQLAdapter.new(options, connection) }
      )

      assert_raises(RuntimeError) do
        BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)
      end
      assert_empty connection.applied_versions
    end
  end

  def test_does_not_split_semicolons_inside_dollar_quoted_blocks
    sql = <<~SQL
      DO $$
      BEGIN
        RAISE NOTICE 'a;b';
      END
      $$;
      CREATE TABLE audit_log (id text PRIMARY KEY);
    SQL

    assert_equal [
      "DO $$\nBEGIN\n  RAISE NOTICE 'a;b';\nEND\n$$",
      "CREATE TABLE audit_log (id text PRIMARY KEY)"
    ], BetterAuth::SQLMigration.statements(sql)
  end

  def test_normalizes_common_database_dialect_aliases
    assert_equal :postgres, BetterAuth::SQLMigration.normalize_dialect("postgresql")
    assert_equal :sqlite, BetterAuth::SQLMigration.normalize_dialect("sqlite3")
  end

  def test_each_dialect_uses_custom_core_model_names_and_quote_styles
    config = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      user: {model_name: "custom_users"},
      session: {model_name: "custom_sessions"},
      account: {model_name: "custom_accounts"},
      verification: {model_name: "custom_verifications"}
    )

    {
      sqlite: {
        quotes: ['CREATE TABLE IF NOT EXISTS "custom_users"', 'FOREIGN KEY ("user_id") REFERENCES "custom_users" ("id")'],
        tables: ['"custom_sessions"', '"custom_accounts"', '"custom_verifications"']
      },
      postgres: {
        quotes: ['CREATE TABLE IF NOT EXISTS "custom_users"', 'FOREIGN KEY ("user_id") REFERENCES "custom_users" ("id")'],
        tables: ['"custom_sessions"', '"custom_accounts"', '"custom_verifications"']
      },
      mysql: {
        quotes: ["CREATE TABLE IF NOT EXISTS `custom_users`", "REFERENCES `custom_users` (`id`)"],
        tables: ["`custom_sessions`", "`custom_accounts`", "`custom_verifications`"]
      },
      mssql: {
        quotes: ["CREATE TABLE [custom_users]", "REFERENCES [custom_users] ([id])"],
        tables: ["[custom_sessions]", "[custom_accounts]", "[custom_verifications]"]
      }
    }.each do |dialect, expectations|
      sql = BetterAuth::SQLMigration.render(config, dialect: dialect, generator: "better_auth-test")

      expectations[:quotes].each { |fragment| assert_includes sql, fragment, dialect.to_s }
      expectations[:tables].each { |fragment| assert_includes sql, fragment, dialect.to_s }
    end
  end

  def test_mysql_and_mssql_bound_indexed_string_columns
    config = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      user: {
        additional_fields: {
          slug: {type: "string", required: false, index: true}
        }
      }
    )

    mysql = BetterAuth::SQLMigration.render(config, dialect: :mysql, generator: "better_auth-test")
    mssql = BetterAuth::SQLMigration.render(config, dialect: :mssql, generator: "better_auth-test")

    assert_includes mysql, "`slug` varchar(191)"
    assert_includes mssql, "[slug] varchar(255)"
    refute_includes mysql, "`slug` text"
    refute_includes mssql, "[slug] varchar(8000)"
  end

  def test_phone_number_plugin_mssql_nullable_unique_uses_filtered_index
    config = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      plugins: [BetterAuth::Plugins.phone_number]
    )
    sql = BetterAuth::SQLMigration.render(config, dialect: :mssql, generator: "better_auth-test")

    refute_includes sql, "CONSTRAINT [uniq_users_phone_number] UNIQUE ([phone_number])"
    assert_includes sql, "CREATE UNIQUE INDEX [uniq_users_phone_number] ON [users] ([phone_number]) WHERE [phone_number] IS NOT NULL"
  end

  # Passkey schema lives in better_auth-passkey; core tests use custom plugin FK cases instead.

  def test_session_additional_fields_via_plugin_match_direct_options
    via_options = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      session: {
        additional_fields: {
          device: {type: "string", required: false}
        }
      }
    )
    via_plugin = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      plugins: [BetterAuth::Plugins.additional_fields(session: {device: {type: "string", required: false}})]
    )

    options_sql = BetterAuth::SQLMigration.render(via_options, dialect: :postgres, generator: "better_auth-test")
    plugin_sql = BetterAuth::SQLMigration.render(via_plugin, dialect: :postgres, generator: "better_auth-test")

    assert_includes options_sql, '"device" text'
    assert_includes plugin_sql, '"device" text'
  end

  def test_migrate_pending_raises_when_sql_execution_fails
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    auth = BetterAuth.auth(
      secret: SECRET,
      database: ->(options) { FakeSQLiteAdapter.new(options, connection) }
    )
    original_execute = connection.method(:execute)
    connection.define_singleton_method(:execute) do |sql, *binds|
      raise "migration statement failed" if sql.match?(/CREATE TABLE IF NOT EXISTS "users"/i)

      original_execute.call(sql, *binds)
    end

    assert_raises(RuntimeError, "migration statement failed") do
      BetterAuth::SQLMigration.migrate_pending(auth)
    end
  end

  def test_migrate_pending_uses_adapter_transaction_when_available
    Dir.mktmpdir("better-auth-core-migrate-transaction") do |dir|
      path = File.join(dir, "transaction.sqlite3")
      adapter = BetterAuth::Adapters::SQLite.new(
        BetterAuth::Configuration.new(secret: SECRET, database: :memory),
        path: path
      )
      transaction_calls = 0
      adapter.define_singleton_method(:transaction) do |&block|
        transaction_calls += 1
        super(&block)
      end
      auth = BetterAuth.auth(secret: SECRET, database: adapter)

      assert BetterAuth::SQLMigration.migrate_pending(auth)
      assert_equal 1, transaction_calls
    end
  end

  def test_migrate_pending_works_with_execute_only_connections
    connection = ExecuteOnlySQLiteConnection.new
    auth = BetterAuth.auth(
      secret: SECRET,
      database: ->(options) { FakeSQLiteAdapter.new(options, connection) }
    )

    assert BetterAuth::SQLMigration.migrate_pending(auth)
    assert connection.executed_statements.any? { |statement| statement.match?(/CREATE TABLE/i) }
  end

  def test_execute_sql_reports_supported_methods_for_invalid_connections
    connection = Object.new

    error = assert_raises(BetterAuth::SQLMigration::UnsupportedAdapterError) do
      BetterAuth::SQLMigration.execute_sql(connection, "SELECT 1")
    end

    assert_includes error.message, "execute, exec, or query"
  end

  class ExecuteOnlySQLiteConnection
    attr_reader :executed_statements

    def initialize
      @executed_statements = []
      @database = SQLite3::Database.new(":memory:")
      @database.results_as_hash = true
    end

    def execute(sql)
      @executed_statements << sql
      @database.execute(sql)
    end
  end
end
